---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 2-demo-source-git-bb-app
  namespace: flux-system
spec:
  interval: 9s
  ref:
    branch: 2-demo
  url: https://github.com/amitkrsau/bb-app-source.git
